import { TABLE_NAMES } from "./tables";

export const PRESETS = {
  "": [],
  CHARACTER: [
    TABLE_NAMES.CHARACTER_SEX,
    TABLE_NAMES.CHARACTER_RACE,
    TABLE_NAMES.CHARACTER_APPEARANCE,
    TABLE_NAMES.CHARACTER_PHYSICAL_DETAIL,
    TABLE_NAMES.CHARACTER_CLOTHES,
    TABLE_NAMES.CHARACTER_PERSONALITY,
    TABLE_NAMES.CHARACTER_MANNERISM,
    TABLE_NAMES.GOTHIC_BACKGROUND,
  ],
  MAGIC: [
    TABLE_NAMES.MAGIC_TABLE_ROLL,
    TABLE_NAMES.MAGIC_PHYSICAL_EFFECTS,
    TABLE_NAMES.MAGIC_PHYSICAL_ELEMENTS,
    TABLE_NAMES.MAGIC_PHYSICAL_FORMS,
    TABLE_NAMES.MAGIC_ETHEREAL_EFFECTS,
    TABLE_NAMES.MAGIC_ETHEREAL_ELEMENTS,
    TABLE_NAMES.MAGIC_ETHEREAL_FORMS,
  ],
};

export const PRESET_LABELS = {
  "": "Choose a preset",
  MAGIC: "Magic Spells",
  CHARACTER: "Character Traits & Personality",
};
